### ISSUE TITLE
fail in render_scenario rule

### ISSUE THREAD

**Issue by moeinzadeh** [snakemake-workflows/dna-seq-varlociraptor#122]
Dear everyone,
I have problem running the snakemake. The stdout/stderr looks like this:

```
Error in rule render_scenario:
    jobid: 39
    output: results/scenarios/A.yaml
    log: logs/render-scenario/A.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 20 of path_to1/dna-seq-varlociraptor/workflow/rules/calling.smk:
Command 'set -euo pipefail; path_to2/bin/python3.10 path_to1/dna-seq-varlociraptor/.snakemake/scripts/tmpe3uwiuwx.render-scenario.py' returned non-zero exit status 1.
  File "path_to1/dna-seq-varlociraptor/workflow/rules/calling.smk", line 20, in __rule_render_scenario
  File "path_to3/miniconda3/envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
```
the content of `logs/render-scenario/A.log` is:
```
path_to1/dna-seq-varlociraptor$ cat logs/render-scenario/A.log
Traceback (most recent call last):
  File "path_to1/dna-seq-varlociraptor/.snakemake/scripts/tmpe3uwiuwx.render-scenario.py", line 15, in <module>
    Template(template.read()).render(
  File "path_to2/miniconda3/envs/snakemake/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "path_to2/miniconda3/envs/snakemake/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 14, in top-level template code
jinja2.exceptions.UndefinedError: pandas.core.series.Series object has no element 0

```
The content of sample.tsv and the units.tsv are: 

sample.tsv
```
path_to1/practic_available_sms/dna-seq-varlociraptor$ cat config/samples.tsv 
sample_name	alias	group	platform	purity	panel
A	A	A	ILLUMINA	NA	NA
```

units.tsv
```

(base)path_to1/dna-seq-varlociraptor$ cat config/units.tsv 
sample_name	unit_name	fq1	fq2	sra	adapters	umis
A	UNAME	path_to_fastq/illumina/fastq/sample_R1.fastq.gz	path_to_fastq/illumina/fastq/sample_R2.fastq.gz	NA	"-a ACGCGATCG -A GCTAGCGTACT"	NA
```
Could you please help me solve this issue?
All the best,
Hossein

**Comment by maryamghr** [comment]
Dear David,
Following this issue, does this tool applicable in germline SV detection for non-cancer samples? if yes, what is the config setting?
Thank you in advance,
Maryam

**Comment by johanneskoester** [comment]
Yes, that is possible. You just have to configure your scenario for searching germline variants (e.g. considering a diploid species in case of human). The scenario to use would be this one: https://varlociraptor.github.io/varlociraptor-scenarios/scenarios/single-sample-germline-prior/
